### ISSUE TITLE
Mask de peso não permite acima de 99.9 

### ISSUE THREAD

**Issue by gabriel-hsb** [rafaoshikawa/calc_imc_react#1]
Olá!
_Primeiramente, adorei a calculadora!_
Porém notei que **não consigo inserir valores acima de 99.9 KG**, provavelmente devido à mascara do React JS sendo utilizada:
![image](https://github.com/rafaoshikawa/calc_imc_react/assets/110293122/c1f74602-0f06-49b4-8b14-6cca24ea53c0)

**Comment by rafaoshikawa** [comment]
Olá gabriel-hsb, fico feliz que tenha gostado da calculadora, e agradeço por compartilhar sua observação! O problema foi solucionado e agora você deverá conseguir inserir valores acima de 99.9 KG sem qualquer dificuldade. Agradecemos por sua paciência e por utilizar nossa calculadora! Se surgir mais alguma dúvida ou se tiver sugestões, estou à disposição para ajudar.

atenciosamente,
Rafael Oshikawa | Engenheiro FrontEnd.
